format = """
[î‚¶](#26233a)\
$username\
[î‚°](bg:#403d52 fg:#26233a)\
$directory\
[î‚°](fg:#403d52 bg:#b4637a)\
$git_branch\
$git_status\
[î‚°](fg:#b4637a bg:#907aa9)\
$nodejs\
$rust\
[î‚° ](fg:#907aa9)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like ï„  to save some space
[username]
show_always = true
style_user = "bg:#26233a"
style_root = "bg:#26233a"
format = '[$user ]($style)'

[directory]
style = "bg:#403d52"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"checkly" = "ğŸ¦"
# "Documents" = "ïœ˜ "
# "Downloads" = "ï€™ "
# "Music" = "ï€ "
# "Pictures" = "ï€¾ "
# Keep in mind that the order matters. For example:
# "Important Documents" = " ïœ˜ï„ª "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important ïœ˜ " = " ïœ˜ï„ª "

[git_branch]
symbol = "îœ§"
# symbol = "ğŸ—‚ "
# symbol = ""
style = "bg:#b4637a"
format = '[[ $symbol $branch ](bg:#b4637a)]($style)'

[git_status]
style = "bg:#b4637a"
format = '[[($all_status$ahead_behind )](bg:#b4637a)]($style)'

[nodejs]
symbol = "îœ˜"
style = "bg:#907aa9"
format = '[[ $symbol ($version) ](bg:#907aa9)]($style)'

[rust]
symbol = "ğŸ¦€"
style = "bg:#907aa9"
format = '[[ $symbol ($version) ](bg:#907aa9)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#907aa9"
format = '[[ â™¥ $time ](bg:#907aa9)]($style)'
